n = int(input())
m = int(input())
k = int(input())
x = int(input())
y = int(input())
z = int(input())
t = int(input())
a = int(input())

one_book = (x + z - n - m - k + t) + (x + y - n - m - k + t) + (y + z - n - m - k + t)
two_book = (n + m - x - t) + (m + k - y - t) + (n + k - z - t)
all_book = a - (one_book + two_book + t)
print(one_book)
print(two_book)
print(all_book)
